# Generated by Django 3.2 on 2023-05-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_auto_20230518_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Код подтверждения'),
        ),
    ]
